### ISSUE TITLE
I get this error below

### ISSUE THREAD

**Issue by hpriergaard** [phillips321/adaudit#10]
Hi
Version 4.1 works ok
****************************************************************************
The lasted lines from 878 to 886

#Dirty fix for .nessus characters (will do this properly or as a function later. Will need more characters adding here...)
$originalnessusoutput = Get-Content $outputdir\adaudit.nessus
$nessusoutput = $originalnessusoutput -Replace "&", "&amp;"
$nessusoutput = $nessusoutput -Replace "`“", "&quot;"
$nessusoutput = $nessusoutput -Replace "ü", "u"
$nessusoutput | Out-File $outputdir\adaudit-replaced.nessus

$endtime = get-date
Write-Both "[*] Script end time $endtime"
****************************************************************************

Version 4.2 didn't works
****************************************************************************
The lasted lines from 879 to 888
#Dirty fix for .nessus characters (will do this properly or as a function later. Will need more characters adding here...)
$originalnessusoutput = Get-Content $outputdir\adaudit.nessus
$nessusoutput = $originalnessusoutput -Replace "&", "&amp;"
$nessusoutput = $nessusoutput -Replace "`Â“", "&quot;"
$nessusoutput = $nessusoutput -Replace "Ã¼", "u"
$nessusoutput | Out-File $outputdir\adaudit-replaced.nessus
~
$endtime = get-date
Write-Both "[*] Script end time $endtime"
~

I run this commando
PS C:\Users\Administrator\Downloads\ADaudit-master> .\AdAudit.ps1 -all
****************************************************************************

Error
At C:\Users\Administrator\Downloads\ADaudit-master\AdAudit.ps1:882 char:48
+ $nessusoutput = $nessusoutput -Replace "`Â“", "&quot;"
+                                                ~
Unexpected token '&' in expression or statement.
At C:\Users\Administrator\Downloads\ADaudit-master\AdAudit.ps1:883 char:41
+ $nessusoutput = $nessusoutput -Replace "Ã¼", "u"
+                                         ~~~~~~~~
Unexpected token 'Ã¼", "u"
$nessusoutput | Out-File $outputdir\adaudit-replaced.nessus
$endtime = get-date
Write-Both "[*]' in expression or statement.
At C:\Users\Administrator\Downloads\ADaudit-master\AdAudit.ps1:887 char:41
+ Write-Both "[*] Script end time $endtime"
+                                         ~
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

Best regards
Henrik

**Comment by thehodown** [comment]
This is now resolved
