### ISSUE TITLE
Password Complexity returns incorrect result.

### ISSUE THREAD

**Issue by Derek000** [phillips321/adaudit#15]
Hi 

I recently ran the script on a server and noticed it returned an incorrect complexity enable result.
We determined that an alternate command fixed the issue.

Instead of using
  (Get-ADDefaultDomainPasswordPolicy).PasswordComplexity
Which may return a blank.

Using the following
  (Get-ADDefaultDomainPasswordPolicy).ComplexityEnabled
Returns “True” as expected.

Thanks for a great tool.

**Comment by phillips321** [comment]
Thanks for the pointers with this, I've fixed it in v4.9. Many thanks
