### ISSUE TITLE
Issue with running on Windows 2008R2 32bit

### ISSUE THREAD

**Issue by vengatesh-nagarajan** [phillips321/adaudit#2]
Missing expression after unary operator '-'.
At C:\Users\Administrator\Downloads\adaudit-master\adaudit-master\AdAudit.ps1:6 char:10
+         -  <<<< added check for transitive trusts

**Comment by phillips321** [comment]
Hi there, This line is simply a comment, so it shouldn't cause the interpreter to even try and do anything. How did you download the script?

**Comment by phillips321** [comment]
I've just changed the line endings, can you try to run again. Many thanks

**Comment by vengatesh-nagarajan** [comment]
You must provide a value expression on the right-hand side of the '-' operator.
At C:\Users\Administrator\Downloads\adaudit-master\adaudit-master\AdAudit.ps1:209 char:146
+         $combinedgpos = ($(((Get-GPInheritance -Target $ouobject).InheritedGpoLinks) | select DisplayName) | ForEach-
Object { $_.DisplayName }) -j <<<< oin ','

**Comment by phillips321** [comment]
Are there any GPOs?
