### ISSUE TITLE
Disabled accounts taken into statistics

### ISSUE THREAD

**Issue by aimarpl** [phillips321/adaudit#8]
Looks like script counts disabled accounts in following reports:
- inactive users
- old passwords
- passwords that do not expire
- computers with old OS

Such accounts are disabled and usually kept for audit purposes, should be included in above provided figures I think.

anyway - nice work!

**Comment by phillips321** [comment]
Good point. I guess correlation between these is important to gain a full understanding of the risk.

If you can suggest a way to do the comparison in powershell please submit a PR

**Comment by thehodown** [comment]
I have filtered out the disabled accounts from the stats/output now.
